import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({
    variable: "--font-Inter",
    subsets: ["latin"],
});

const lora = Lora({
    variable: "--font-Lora",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "David Lee | Frontend Developer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} ${lora.variable} antialiased customWidth`}>
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
